# Generated by Django 4.0 on 2022-03-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarraProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(max_length=2)),
                ('mov', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=500)),
            ],
        ),
    ]
