# Generated by Django 4.0 on 2022-03-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preditor', '0003_barraprogresso_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barraprogresso',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preditor.projeto'),
        ),
        migrations.AlterField(
            model_name='barraprogresso',
            name='processo',
            field=models.CharField(max_length=10),
        ),
    ]
