# Generated by Django 4.0 on 2022-10-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preditor', '0007_classemodelo_areamodelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Satelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('bandReferencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='areamodelo',
            old_name='classeModelo',
            new_name='classe',
        ),
        migrations.RemoveField(
            model_name='areamodelo',
            name='modelo',
        ),
        migrations.CreateModel(
            name='TipoItemFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=200)),
                ('raster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preditor.raster')),
            ],
        ),
        migrations.CreateModel(
            name='RasterIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preditor.raster')),
            ],
        ),
        migrations.CreateModel(
            name='RasterBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=200)),
                ('tagOnSat', models.CharField(max_length=200)),
                ('raster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preditor.raster')),
                ('satelite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preditor.satelite')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasterIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preditor.rasterindex')),
                ('tipoItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preditor.tipoitemformula')),
            ],
        ),
    ]
