# Generated by Django 4.0 on 2022-10-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preditor', '0010_raster_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='stack',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
