# Generated by Django 4.0 on 2022-10-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preditor', '0011_modelo_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raster',
            name='formula',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
