# Generated by Django 4.0 on 2022-10-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('preditor', '0012_alter_raster_formula_alter_raster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='url',
        ),
        migrations.AddField(
            model_name='raster',
            name='publica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raster',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
